@startuml
Left to Right Direction
skinParam packageStyle rectangle
actor Guru
actor Walikelas

rectangle "Aplikasi Penilaian Kurikulum 2013"{

    Guru -- (Menambah Data Mengajar)
    Guru -- (Melihat Daftar Siswa)
    Guru -- (Mengelola Nilai Siswa)
    Guru -- (Mencetak Rekap Nilai)
    Guru -- (Melihat Data Siswa)
    Walikelas -- (Melihat Daftar Siswa)
    Walikelas -- (Melihat Data Siswa)
    Walikelas -- (Mengelola Nilai Rapor Siswa)
    Walikelas -- (Mencetak Rapor Siswa)
    Walikelas -- (Mencetak Transkrip Nilai Siswa)

    (Menambah Data Mengajar)..> (Login) : include
    (Mengelola Nilai Siswa)..> (Login) : include
    (Mencetak Rekap Nilai)..> (Login) : include

    (Melihat Daftar Siswa)..> (Login) : include
    (Melihat Data Siswa)..> (Login) : include
    (Mengelola Nilai Rapor Siswa)..> (Login) : include
    (Mencetak Rapor Siswa)..> (Login) : include
    (Mencetak Transkrip Nilai Siswa)..> (Login) : include

}

@enduml